# Generated by Django 4.1.7 on 2023-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('math_score', models.CharField(max_length=10)),
                ('chinese_score', models.CharField(max_length=10)),
                ('english_score', models.CharField(max_length=10)),
                ('total_score', models.CharField(max_length=10)),
            ],
        ),
    ]
