# Generated by Django 4.1.7 on 2023-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_student',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
    ]
